# Generated by Django 5.1.5 on 2025-02-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0002_alter_note_categoryid_alter_note_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
